### PR TITLE
Show errors raised inside test scripts

### PR DESCRIPTION
**Pull request by dazld**
Working on this, but noticed that errors raised were not shown, and the task continued regardless.

### CODE REVIEW

**Comment by matchett808** [comment]
I'll test this over the next few days && merge if appropriate :)

**Comment by matchett808** [comment]
closing pull request as it introduced other issues, however I've added some of the code to get the error printing working, also prettyfied

**Comment by matchett808** [comment]
- I'm committing as we speak

**Comment by dazld** [comment]
thanks, I'll try it out!

**Pull request closed without merging**
